### ISSUE TITLE
Would you like to contribute some features back to wong2/chat-gpt-google-extension ?

### ISSUE THREAD

**Issue by wong2** [TaylorHawkes/ChatGPTBrowserExtension#1]

**Comment by TaylorHawkes** [comment]
Hey Wong, I have a somewhat different vision for how I wanted to make this extension function, so some features may not make sense/work correctly in “ChatGPT for Google”.  But yea, if you see features from here that do make sense to add in, I'd be happy to contribute/make PR to get them in.... But beware my code is much sloppier than yours ;-)
